module.exports = {
    ACTION_ADD: "ACTION_ADD_DISCIPLINE",
    ACTION_REMOVE: "ACTION_REMOVE_DISCIPLINE",
    ACTION_EDIT: "ACTION_EDIT_DISCIPLINE",
    ACTION_UPDATE: "ACTION_UPDATE_DISCIPLINE",
    ACTION_UPDATE: "ACTION_SEARCH_DISCIPLINE",
}
