module.exports = {
    ACTION_ADD: "ACTION_ADD_DOCUMENT",
    ACTION_REMOVE: "ACTION_REMOVE_DOCUMENT",
    ACTION_EDIT: "ACTION_EDIT_DOCUMENT",
    ACTION_UPDATE: "ACTION_UPDATE_DOCUMENT",
    ACTION_UPDATE: "ACTION_SEARCH_DOCUMENT",
}
