module.exports = {
    ACTION_ADD: "ACTION_ADD_EDUCATION",
    ACTION_REMOVE: "ACTION_REMOVE_EDUCATION",
    ACTION_EDIT: "ACTION_EDIT_EDUCATION",
    ACTION_UPDATE: "ACTION_UPDATE_EDUCATION",
    ACTION_UPDATE: "ACTION_SEARCH_EDUCATION",
}
