module.exports = {
    ACTION_ADD: "ACTION_ADD_EXPERIENCE",
    ACTION_REMOVE: "ACTION_REMOVE_EXPERIENCE",
    ACTION_EDIT: "ACTION_EDIT_EXPERIENCE",
    ACTION_UPDATE: "ACTION_UPDATE_EXPERIENCE",
    ACTION_UPDATE: "ACTION_SEARCH_EXPERIENCE",
}
