module.exports = {
    ACTION_ADD: "ACTION_ADD_LICENSE",
    ACTION_REMOVE: "ACTION_REMOVE_LICENSE",
    ACTION_EDIT: "ACTION_EDIT_LICENSE",
    ACTION_UPDATE: "ACTION_UPDATE_LICENSE",
    ACTION_UPDATE: "ACTION_SEARCH_LICENSE",
}
