module.exports = {
    ACTION_ADD: "ACTION_ADD_PERSON",
    ACTION_REMOVE: "ACTION_REMOVE_PERSON",
    ACTION_EDIT: "ACTION_EDIT_PERSON",
    ACTION_UPDATE: "ACTION_UPDATE_PERSON",
    ACTION_UPDATE: "ACTION_SEARCH_PERSON",
    ACTION_CLEAR: "ACTION_CLEAR_PERSON",
}
