module.exports = {
    ACTION_ADD: "ACTION_ADD_PERSON",
    ACTION_REMOVE: "ACTION_REMOVE_PERSON",
    ACTION_EDIT: "ACTION_EDIT_PERSON",
    ACTION_UPDATE: "ACTION_UPDATE_PERSON",
    ACTION_UPDATE_LIST: "ACTION_UPDATE_LIST_PERSON",
    ACTION_SEARCH: "ACTION_SEARCH_PERSON",
    ACTION_SEARCH_BY_RECENSION: "ACTION_SEARCH_BY_RECENSION",
    ACTION_ADD_TO_RECENSION: "ACTION_ADD_TO_RECENSION",
    ACTION_CLEAR: "ACTION_CLEAR_PERSON",
}
