module.exports = {
    ACTION_ADD: "ACTION_ADD_RECENSION",
    ACTION_REMOVE: "ACTION_REMOVE_RECENSION",
    ACTION_EDIT: "ACTION_EDIT_RECENSION",
    ACTION_EDIT_DETAIL: "ACTION_EDIT_DETAIL_RECENSION",
    ACTION_CLOSE_DETAIL: "ACTION_CLOSE_DETAIL_RECENSION",
    ACTION_UPDATE: "ACTION_UPDATE_RECENSION",
    ACTION_SEARCH: "ACTION_SEARCH_RECENSION",
}
